<a href="https://colab.research.google.com/github/neel786/Numpy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World")

Hello World


# Creating NumPy Array


In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr3=np.zeros((3,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr4=np.ones((4,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr5=np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
arr5a=np.eye(4)
arr5a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
arr6=np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr7=np.arange(5,20)
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
arr8=np.arange(10,20,2)
arr8

array([10, 12, 14, 16, 18])

In [ ]:
arr9=np.linspace(10,20,10)
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
arr10=arr9.copy()
arr10

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

# Python List vs Array

**less memory**

In [ ]:
lista=range(100)
arr11=np.arange(100)

In [ ]:
import sys

In [ ]:
print(sys.getsizeof(10)*len(lista))

2800


In [ ]:
print(arr11.itemsize*arr11.size)

800


**Faster**

In [ ]:
import time

In [28]:
x=range(10000000)
y=range(10000000,20000000)

start_time=time.time()

c=[(x,y) for x,y in zip(x,y)]

print(time.time()-start_time)

5.273119211196899


In [29]:
a=np.arange(10000000)
b=np.arange(10000000,20000000)

start_time=time.time()

c=a + b

print(time.time()-start_time)

0.7186460494995117
